# Schema for the configuration files of the Joinup user module.
joinup_user.mail:
 type: config_object
 label: 'Email settings'
 mapping:
  email_admin_update:
    type: mail
    label: 'Account updated by administrator confirmation'
  og_roles_changed:
    type: mail
    label: 'Og roles changed'
  password_reset_confirm:
    type: mail
    label: 'Password reset confirmation'
