taxonomy.vocabulary.*.third_party.rdf_entity:
  type: mapping
  label: 'RDF Entity third party settings'
  mapping:
    rdf_type:
      type: string
      label: 'Rdf type mapping'
    graph:
      type: sequence
      sequence:
        type: string
        label: 'The mapping of a graph definition to a graph uri.'
    mapping:
      type: sequence
      label: 'Property'
      sequence:
        type: sequence
        label: 'Column'
        sequence:
          type: mapping
          mapping:
            predicate:
              type: string
              label: 'Predicate'
            format:
              type: string
              label: 'Value format'
    entity_id_plugin:
      type: string
      label: 'The plugin that generates the entity ID'

taxonomy.vocabulary.*.third_party.rdf_taxonomy:
  type: mapping
  label: 'RDF Taxonomy third party settings'
  mapping:
    locked:
      type: boolean
      label: 'If true, terms cannot be added or edited via UI'
