# Schema for the configuration files of the rdf_entity module.

rdf_entity.rdfentity.*:
  type: config_entity
  label: 'Rdf type'
  mapping:
    name:
      type: label
      label: 'Name'
    rid:
      type: string
      label: 'Bundle type'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'

rdf_entity.rdfentity.*.third_party.rdf_entity:
  type: mapping
  label: 'Third party settings'
  mapping:
    rdf_type:
      type: string
      label: 'Rdf type mapping'
    graph:
      type: sequence
      sequence:
        type: string
        label: 'The mapping of a graph definition to a graph uri.'
    mapping:
      type: sequence
      label: 'Property'
      sequence:
        type: sequence
        label: 'Column'
        sequence:
          type: mapping
          mapping:
            predicate:
              type: string
              label: 'Predicate'
            format:
              type: string
              label: 'Value format'
    entity_id_plugin:
      type: string
      label: 'The plugin that generates the entity ID'

field.storage.*.*.third_party.rdf_entity:
  type: mapping
  mapping:
    'mapping':
      type: sequence
      label: 'Column'
      sequence:
        type: mapping
        mapping:
          predicate:
            type: string
            label: 'Predicate'
          format:
            type: string
            label: 'Value format'

field.widget.settings.auto_uri:
  type: mapping
  label: 'Settings regarding the uri field.'
  mapping:
    prefix:
      type: string
      label: 'Behaviour'

field.widget.settings.datetime_create_update:
  type: mapping
  label: 'Behaviour of the field'
  mapping:
    behaviour:
      type: string
      label: 'Behaviour'

field.formatter.third_party.joinup:
  type: mapping
  label: 'Theme settings for Joinup project.'
  mapping:
    template_suggestion:
      type: string
