collection.settings:
  type: config_object
  label: 'Collection workflow permission settings'
  mapping:
    transitions:
      type: sequence
      label: 'Allowed transitions'
      sequence:
        type: sequence
        label: 'Target state'
        sequence:
          type: sequence
          label: 'Source state'
          sequence:
            type: string
            label: 'Role'

# Schema for the og menu.
block.settings.collection_menu_block:*:
  type: block_settings
  label: 'Og menu block settings'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
