<?php

/**
 * @file
 * Contains form_auto_fill.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Component\Uuid\Php;

/**
 * Implements hook_entity_prepare_form().
 *
 * Randomly fills each required field with a random value. For file fields,
 * use default objects provided by the module.
 * The random filling, skips all entity keys except from the label as they
 * should not be handled within the form.
 */
function form_auto_fill_entity_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  if (!$entity->isNew()) {
    return;
  }
  $settings = \Drupal::config('form_auto_fill.settings');

  // If the auto fill is disabled, return.
  if ($settings->get('activate_auto_fill') == FALSE) {
    return;
  }

  // Skip fields handled by core (label will still be filled later on).
  $keys_to_skip = $entity->getEntityType()->getKeys();
  $uuid = new Php();
  $auto_fill_types = $settings->get('fields_to_fill');

  if (in_array('label', $auto_fill_types)) {
    $entity->set('label', $uuid->generate());
  }

  $field_definitions = $entity->getFieldDefinitions();
  foreach ($field_definitions as $id => $field_definition) {
    if (in_array($id, $keys_to_skip)) {
      continue;
    }

    if ($field_definition->isRequired() && in_array('required', $auto_fill_types)) {
      $entity->{$id}->generateSampleItems();
    }
    elseif ((!$field_definition->isRequired()) && in_array('optional', $auto_fill_types)) {
      $entity->{$id}->generateSampleItems();
    }
  }

}
