rdf_draft.settings:
 type: config_object
 label: 'Email settings'
 mapping:
  revision_bundle_rdf_entity:
    type: sequence
    sequence:
      type: string
  default_save_graph_rdf_entity:
    type: string
  revision_bundle_taxonomy_term:
    type: sequence
    sequence:
      type: string
  default_save_graph_taxonomy_term:
    type: string
