<?php

/**
 * @file
 * Contains id_awesome_module.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Component\Uuid\Php;

define('ID_AWESOME_MODULE_FILE_DIRECTORY', drupal_get_path('module', 'id_awesome_module') . '/includes');

/**
 * Implements hook_entity_prepare_form().
 *
 * Randomly fills each required field with a random value. For file fields,
 * use default objects provided by the module.
 * The random filling, skips all entity keys except from the label as they
 * should not be handled within the form.
 */
function id_awesome_module_entity_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  if (!$entity->isNew()) {
    return;
  }
  $uuid = new Php();

  // Fill in label but skip the rest of the entity keys.
  $keys_to_skip = $entity->getEntityType()->getKeys();
  $entity->set('label', $uuid->generate());

  $field_definitions = $entity->getFieldDefinitions();
  foreach ($field_definitions as $id => $field_definition) {
    if (in_array($id, $keys_to_skip) || !$field_definition->isRequired()) {
      continue;
    }

    $entity->{$id}->generateSampleItems();
  }

}
