field.formatter.settings.tracked_hosted_file_download:
  type: mapping
  label: 'Tracked hosted file download formatter settings'
  mapping:
    hosted_files_title:
      type: string
      label: 'The link title for hosted files'
    remote_files_title:
      type: string
      label: 'The link title for remote files'
    show_remote_files:
      type: boolean
      label: 'A boolean to indicate if the remote files should be shown'
